name: Java Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: maven
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Test
        run: mvn -B test --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
